version: 2
updates:
  - package-ecosystem: "github-actions"
    # Look for .github/workflow/*.yml
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"