name = "ModelShortcodes"
uuid = "1b812b80-aa2a-4b8d-8409-4811a979d73e"
authors = ["Wen Wei Tseng <sosiristseng@gmail.com>"]
version = "0.3.0"

[deps]
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
