name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1.6
        with:
          version: '1.6'
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        run: julia -e 'using CompatHelper; CompatHelper.main()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
